CREATE TABLE users (
                       user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(50) NOT NULL,
                       email VARCHAR(50) NOT NULL UNIQUE,
                       role VARCHAR(20) NOT NULL
);

CREATE TABLE contacts (
                          contact_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(50) NOT NULL,
                          surname VARCHAR(50) NOT NULL,
                          email VARCHAR(50),
                          phone_number VARCHAR(20)
);

CREATE TABLE user_contacts (
                               user_id int REFERENCES users(user_id) ON DELETE CASCADE,
                               contact_id int REFERENCES contacts(contact_id) ON DELETE CASCADE,
                               PRIMARY KEY (user_id, contact_id)
);